queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Node.js CI

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - check-success=build (14.x)
      - check-success=build (16.x)
      - check-success=build (18.x)
    actions:
      queue:
        name: default
