queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=CI

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - check-success=Wait for CI
    actions:
      queue:
        name: default
