name: Merge Queue

on:
  pull_request:
    branches:
      - main

jobs:
  wait-pr-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait PR CI to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ github.token }}
          running-workflow-name: "Wait PR CI"
          # Captures required CI job names, including dynamic matrix jobs
          check-regexp: ^build$
