name: Merge Queue

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Wait for CI
      uses: lewagon/wait-on-check-action@v1
      with:
        check-name: '**'
