name: Merge Queue

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Wait for CI
      uses: peter-evans/wait-for-status-checks@v3
      with:
        require: all
